apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j2i02wx3g-nodejs 
  janus-idp.io/tekton: j2i02wx3g-nodejs
  backstage.io/kubernetes-id: j2i02wx3g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j2i02wx3g-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml